# Generated by Django 5.1.3 on 2024-12-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
